// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO apikeys (
    id ,
    developer_id,
    key_hash,
    last_used_at,
    revoked_at 
) VALUES ($1,$2,$3,$4,$5)
RETURNING id, developer_id, key_hash
`

type CreateApiKeyParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	KeyHash     string
	LastUsedAt  sql.NullTime
	RevokedAt   sql.NullTime
}

type CreateApiKeyRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	KeyHash     string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createApiKey,
		arg.ID,
		arg.DeveloperID,
		arg.KeyHash,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	var i CreateApiKeyRow
	err := row.Scan(&i.ID, &i.DeveloperID, &i.KeyHash)
	return i, err
}

const getApiKey = `-- name: GetApiKey :one
SELECT id, developer_id , last_used_at ,revoked_at from apikeys where key_hash =$1
`

type GetApiKeyRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	LastUsedAt  sql.NullTime
	RevokedAt   sql.NullTime
}

func (q *Queries) GetApiKey(ctx context.Context, keyHash string) (GetApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getApiKey, keyHash)
	var i GetApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeApiKey = `-- name: RevokeApiKey :one
DELETE FROM apikeys WHERE id=$1 RETURNING id,last_used_at, revoked_at
`

type RevokeApiKeyRow struct {
	ID         uuid.UUID
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

func (q *Queries) RevokeApiKey(ctx context.Context, id uuid.UUID) (RevokeApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, revokeApiKey, id)
	var i RevokeApiKeyRow
	err := row.Scan(&i.ID, &i.LastUsedAt, &i.RevokedAt)
	return i, err
}
