// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO apikeys (
    id ,
    developer_id,
    name,
    key_hash,
    last_used_at,
    revoked_at 
) VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, developer_id, name, key_hash
`

type CreateApiKeyParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	KeyHash     string
	LastUsedAt  sql.NullTime
	RevokedAt   sql.NullTime
}

type CreateApiKeyRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	KeyHash     string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, createApiKey,
		arg.ID,
		arg.DeveloperID,
		arg.Name,
		arg.KeyHash,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	var i CreateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.KeyHash,
	)
	return i, err
}

const getApiKey = `-- name: GetApiKey :one
SELECT id, developer_id, name, last_used_at, revoked_at from apikeys where key_hash =$1
`

type GetApiKeyRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	LastUsedAt  sql.NullTime
	RevokedAt   sql.NullTime
}

func (q *Queries) GetApiKey(ctx context.Context, keyHash string) (GetApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getApiKey, keyHash)
	var i GetApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserApiKeys = `-- name: GetUserApiKeys :many

SELECT
    a.id,
    a.name,
    a.last_used_at,
    a.revoked_at,
    a.created_at,
    COALESCE(b.api_requests, 0) AS api_requests,
    COALESCE(b.mailbox_requests, 0) AS mailbox_requests,
    COALESCE(b.message_requests, 0) AS message_requests
FROM apikeys a
LEFT JOIN api_key_usage b
    ON b.api_key_id = a.id
   AND b.period = DATE_TRUNC('month', CURRENT_DATE)::DATE
WHERE a.developer_id = $1
`

type GetUserApiKeysRow struct {
	ID              uuid.UUID
	Name            string
	LastUsedAt      sql.NullTime
	RevokedAt       sql.NullTime
	CreatedAt       sql.NullTime
	ApiRequests     int32
	MailboxRequests int32
	MessageRequests int32
}

func (q *Queries) GetUserApiKeys(ctx context.Context, developerID uuid.UUID) ([]GetUserApiKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserApiKeys, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserApiKeysRow
	for rows.Next() {
		var i GetUserApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.ApiRequests,
			&i.MailboxRequests,
			&i.MessageRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE apikeys
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE id = $1
RETURNING id, last_used_at, revoked_at
`

type RevokeApiKeyRow struct {
	ID         uuid.UUID
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

func (q *Queries) RevokeApiKey(ctx context.Context, id uuid.UUID) (RevokeApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, revokeApiKey, id)
	var i RevokeApiKeyRow
	err := row.Scan(&i.ID, &i.LastUsedAt, &i.RevokedAt)
	return i, err
}

const revokeDeveloperApiKey = `-- name: RevokeDeveloperApiKey :one
UPDATE apikeys
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE id = $1 AND developer_id = $2
RETURNING id, last_used_at, revoked_at
`

type RevokeDeveloperApiKeyParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

type RevokeDeveloperApiKeyRow struct {
	ID         uuid.UUID
	LastUsedAt sql.NullTime
	RevokedAt  sql.NullTime
}

func (q *Queries) RevokeDeveloperApiKey(ctx context.Context, arg RevokeDeveloperApiKeyParams) (RevokeDeveloperApiKeyRow, error) {
	row := q.db.QueryRowContext(ctx, revokeDeveloperApiKey, arg.ID, arg.DeveloperID)
	var i RevokeDeveloperApiKeyRow
	err := row.Scan(&i.ID, &i.LastUsedAt, &i.RevokedAt)
	return i, err
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :one
UPDATE apikeys
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, last_used_at
`

type UpdateApiKeyLastUsedRow struct {
	ID         uuid.UUID
	LastUsedAt sql.NullTime
}

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id uuid.UUID) (UpdateApiKeyLastUsedRow, error) {
	row := q.db.QueryRowContext(ctx, updateApiKeyLastUsed, id)
	var i UpdateApiKeyLastUsedRow
	err := row.Scan(&i.ID, &i.LastUsedAt)
	return i, err
}
