// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key_usage.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const incrementApiKeyUsage = `-- name: IncrementApiKeyUsage :one
INSERT INTO api_key_usage (
    api_key_id,
    period,
    api_requests,
    mailbox_requests,
    message_requests
)
VALUES (
    $1,
    DATE_TRUNC('month', CURRENT_DATE)::DATE,
    $2,
    CASE WHEN $3 = 'mailbox' THEN $2 ELSE 0 END,
    CASE WHEN $3 = 'message' THEN $2 ELSE 0 END
)
ON CONFLICT (api_key_id, period)
DO UPDATE SET
    api_requests = api_key_usage.api_requests + EXCLUDED.api_requests,
    mailbox_requests = api_key_usage.mailbox_requests + EXCLUDED.mailbox_requests,
    message_requests = api_key_usage.message_requests + EXCLUDED.message_requests
RETURNING api_key_id, period, api_requests, mailbox_requests, message_requests
`

type IncrementApiKeyUsageParams struct {
	ApiKeyID    uuid.UUID
	ApiRequests int32
	Category    interface{}
}

func (q *Queries) IncrementApiKeyUsage(ctx context.Context, arg IncrementApiKeyUsageParams) (ApiKeyUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementApiKeyUsage, arg.ApiKeyID, arg.ApiRequests, arg.Category)
	var i ApiKeyUsage
	err := row.Scan(
		&i.ApiKeyID,
		&i.Period,
		&i.ApiRequests,
		&i.MailboxRequests,
		&i.MessageRequests,
	)
	return i, err
}
