// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_usage.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const incrementUsage = `-- name: IncrementUsage :one
INSERT INTO developer_usage (
    developer_id,
    period,
    api_requests
)
VALUES (
    $1,
    DATE_TRUNC('month', CURRENT_DATE)::DATE,
    1
)
ON CONFLICT (developer_id, period)
DO UPDATE SET
    api_requests = developer_usage.api_requests + 1
RETURNING developer_id, period, api_requests, mailboxes_created, messages_received
`

func (q *Queries) IncrementUsage(ctx context.Context, developerID uuid.UUID) (DeveloperUsage, error) {
	row := q.db.QueryRowContext(ctx, incrementUsage, developerID)
	var i DeveloperUsage
	err := row.Scan(
		&i.DeveloperID,
		&i.Period,
		&i.ApiRequests,
		&i.MailboxesCreated,
		&i.MessagesReceived,
	)
	return i, err
}
