// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: developer.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createDeveloper = `-- name: CreateDeveloper :one
INSERT INTO developer (
    id ,
    name,
    email
) VALUES ($1,$2,$3)
RETURNING id, name,email
`

type CreateDeveloperParams struct {
	ID    uuid.UUID
	Name  string
	Email string
}

type CreateDeveloperRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) CreateDeveloper(ctx context.Context, arg CreateDeveloperParams) (CreateDeveloperRow, error) {
	row := q.db.QueryRowContext(ctx, createDeveloper, arg.ID, arg.Name, arg.Email)
	var i CreateDeveloperRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
