// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: developer.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeveloper = `-- name: CreateDeveloper :one
INSERT INTO developer (
    id ,
    name,
    email
) VALUES ($1,$2,$3)
RETURNING id, name,email
`

type CreateDeveloperParams struct {
	ID    uuid.UUID
	Name  string
	Email string
}

type CreateDeveloperRow struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) CreateDeveloper(ctx context.Context, arg CreateDeveloperParams) (CreateDeveloperRow, error) {
	row := q.db.QueryRowContext(ctx, createDeveloper, arg.ID, arg.Name, arg.Email)
	var i CreateDeveloperRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getDeveloper = `-- name: GetDeveloper :one

SELECT
    d.name,
    d.email,
    d.api_quota,
    d.mailbox_quota,
    d.message_quota,
    d.created_at,
    COALESCE(du.api_requests, 0) AS api_requests,
    COALESCE(du.mailbox_requests, 0) AS mailbox_requests,
    COALESCE(du.messages_requests, 0) AS messages_requests
FROM developer d
LEFT JOIN developer_usage du
    ON d.id = du.developer_id
   AND du.period = DATE_TRUNC('month', CURRENT_DATE)::DATE
WHERE d.id = $1
`

type GetDeveloperRow struct {
	Name             string
	Email            string
	ApiQuota         int32
	MailboxQuota     int32
	MessageQuota     int32
	CreatedAt        sql.NullTime
	ApiRequests      int32
	MailboxRequests  int32
	MessagesRequests int32
}

func (q *Queries) GetDeveloper(ctx context.Context, id uuid.UUID) (GetDeveloperRow, error) {
	row := q.db.QueryRowContext(ctx, getDeveloper, id)
	var i GetDeveloperRow
	err := row.Scan(
		&i.Name,
		&i.Email,
		&i.ApiQuota,
		&i.MailboxQuota,
		&i.MessageQuota,
		&i.CreatedAt,
		&i.ApiRequests,
		&i.MailboxRequests,
		&i.MessagesRequests,
	)
	return i, err
}
