// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailAddress = `-- name: CreateEmailAddress :one
INSERT INTO mailboxes(
    id , address , expires_at
) 
VALUES ($1,$2,$3) 
ON CONFLICT(address)
DO UPDATE SET expires_at= EXCLUDED.expires_at
Returning address, created_at, expires_at
`

type CreateEmailAddressParams struct {
	ID        uuid.UUID
	Address   string
	ExpiresAt time.Time
}

type CreateEmailAddressRow struct {
	Address   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailAddress(ctx context.Context, arg CreateEmailAddressParams) (CreateEmailAddressRow, error) {
	row := q.db.QueryRowContext(ctx, createEmailAddress, arg.ID, arg.Address, arg.ExpiresAt)
	var i CreateEmailAddressRow
	err := row.Scan(&i.Address, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const getMailboxId = `-- name: GetMailboxId :one
SELECT id from mailboxes where address=$1
`

func (q *Queries) GetMailboxId(ctx context.Context, address string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getMailboxId, address)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertMailbox = `-- name: UpsertMailbox :one

INSERT INTO mailboxes (
    id,
    address,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (address)
DO UPDATE SET address = EXCLUDED.address
RETURNING id, address, created_at, expires_at
`

type UpsertMailboxParams struct {
	ID        uuid.UUID
	Address   string
	ExpiresAt time.Time
}

func (q *Queries) UpsertMailbox(ctx context.Context, arg UpsertMailboxParams) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, upsertMailbox, arg.ID, arg.Address, arg.ExpiresAt)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
