// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailAddress = `-- name: CreateEmailAddress :many
INSERT INTO mailboxes(
    id , address , expires_at
) 
VALUES ($1,$2,$3) 
ON CONFLICT(address)
DO UPDATE SET expires_at= EXCLUDED.expires_at
Returning address, created_at, expires_at
`

type CreateEmailAddressParams struct {
	ID        uuid.UUID
	Address   string
	ExpiresAt time.Time
}

type CreateEmailAddressRow struct {
	Address   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailAddress(ctx context.Context, arg CreateEmailAddressParams) ([]CreateEmailAddressRow, error) {
	rows, err := q.db.QueryContext(ctx, createEmailAddress, arg.ID, arg.Address, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateEmailAddressRow
	for rows.Next() {
		var i CreateEmailAddressRow
		if err := rows.Scan(&i.Address, &i.CreatedAt, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
