// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomEmailAddress = `-- name: CreateCustomEmailAddress :one
INSERT INTO mailboxes(
    id, address, expires_at, created_by
)
VALUES ($1, $2, $3, $4)
ON CONFLICT(address) DO NOTHING
RETURNING address, created_at, expires_at, created_by
`

type CreateCustomEmailAddressParams struct {
	ID        uuid.UUID
	Address   string
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

type CreateCustomEmailAddressRow struct {
	Address   string
	CreatedAt time.Time
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateCustomEmailAddress(ctx context.Context, arg CreateCustomEmailAddressParams) (CreateCustomEmailAddressRow, error) {
	row := q.db.QueryRowContext(ctx, createCustomEmailAddress,
		arg.ID,
		arg.Address,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateCustomEmailAddressRow
	err := row.Scan(
		&i.Address,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const createEmailAddress = `-- name: CreateEmailAddress :one
INSERT INTO mailboxes(
    id , address , expires_at, created_by
) 
VALUES ($1,$2,$3,$4)
ON CONFLICT(address)
DO UPDATE SET
    expires_at = EXCLUDED.expires_at,
    created_by = COALESCE(EXCLUDED.created_by, mailboxes.created_by)
RETURNING address, created_at, expires_at, created_by
`

type CreateEmailAddressParams struct {
	ID        uuid.UUID
	Address   string
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

type CreateEmailAddressRow struct {
	Address   string
	CreatedAt time.Time
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateEmailAddress(ctx context.Context, arg CreateEmailAddressParams) (CreateEmailAddressRow, error) {
	row := q.db.QueryRowContext(ctx, createEmailAddress,
		arg.ID,
		arg.Address,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateEmailAddressRow
	err := row.Scan(
		&i.Address,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteDeveloperMailboxByID = `-- name: DeleteDeveloperMailboxByID :one
DELETE FROM mailboxes
WHERE id = $1 AND created_by = $2
RETURNING id, address
`

type DeleteDeveloperMailboxByIDParams struct {
	ID        uuid.UUID
	CreatedBy uuid.NullUUID
}

type DeleteDeveloperMailboxByIDRow struct {
	ID      uuid.UUID
	Address string
}

func (q *Queries) DeleteDeveloperMailboxByID(ctx context.Context, arg DeleteDeveloperMailboxByIDParams) (DeleteDeveloperMailboxByIDRow, error) {
	row := q.db.QueryRowContext(ctx, deleteDeveloperMailboxByID, arg.ID, arg.CreatedBy)
	var i DeleteDeveloperMailboxByIDRow
	err := row.Scan(&i.ID, &i.Address)
	return i, err
}

const deleteExpiredMailbox = `-- name: DeleteExpiredMailbox :many
WITH deleted AS (
    DELETE FROM mailboxes 
    WHERE expires_at<$1 RETURNING id
)
SELECT id FROM deleted
`

func (q *Queries) DeleteExpiredMailbox(ctx context.Context, expiresAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredMailbox, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMailbox = `-- name: DeleteMailbox :one
DELETE FROM mailboxes
WHERE address = $1 AND created_by = $2
RETURNING id, address
`

type DeleteMailboxParams struct {
	Address   string
	CreatedBy uuid.NullUUID
}

type DeleteMailboxRow struct {
	ID      uuid.UUID
	Address string
}

func (q *Queries) DeleteMailbox(ctx context.Context, arg DeleteMailboxParams) (DeleteMailboxRow, error) {
	row := q.db.QueryRowContext(ctx, deleteMailbox, arg.Address, arg.CreatedBy)
	var i DeleteMailboxRow
	err := row.Scan(&i.ID, &i.Address)
	return i, err
}

const getDeveloperMailboxByID = `-- name: GetDeveloperMailboxByID :one
SELECT id, address, created_at, expires_at, created_by
FROM mailboxes
WHERE id = $1 AND created_by = $2
`

type GetDeveloperMailboxByIDParams struct {
	ID        uuid.UUID
	CreatedBy uuid.NullUUID
}

func (q *Queries) GetDeveloperMailboxByID(ctx context.Context, arg GetDeveloperMailboxByIDParams) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, getDeveloperMailboxByID, arg.ID, arg.CreatedBy)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDeveloperMailboxId = `-- name: GetDeveloperMailboxId :one
SELECT id
FROM mailboxes
WHERE address = $1 AND created_by = $2
`

type GetDeveloperMailboxIdParams struct {
	Address   string
	CreatedBy uuid.NullUUID
}

func (q *Queries) GetDeveloperMailboxId(ctx context.Context, arg GetDeveloperMailboxIdParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getDeveloperMailboxId, arg.Address, arg.CreatedBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getExpiredMailboxIDs = `-- name: GetExpiredMailboxIDs :many
SELECT id
FROM mailboxes
WHERE expires_at < $1
`

func (q *Queries) GetExpiredMailboxIDs(ctx context.Context, expiresAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredMailboxIDs, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailboxCreatedBy = `-- name: GetMailboxCreatedBy :one
SELECT created_by
FROM mailboxes
WHERE id = $1
`

func (q *Queries) GetMailboxCreatedBy(ctx context.Context, id uuid.UUID) (uuid.NullUUID, error) {
	row := q.db.QueryRowContext(ctx, getMailboxCreatedBy, id)
	var created_by uuid.NullUUID
	err := row.Scan(&created_by)
	return created_by, err
}

const getMailboxId = `-- name: GetMailboxId :one
SELECT id from mailboxes where address=$1
`

func (q *Queries) GetMailboxId(ctx context.Context, address string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getMailboxId, address)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPublicMailboxId = `-- name: GetPublicMailboxId :one
SELECT id
FROM mailboxes
WHERE address = $1 AND created_by IS NULL
`

func (q *Queries) GetPublicMailboxId(ctx context.Context, address string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPublicMailboxId, address)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listDeveloperMailboxes = `-- name: ListDeveloperMailboxes :many
SELECT id, address, created_at, expires_at
FROM mailboxes
WHERE created_by = $1
ORDER BY created_at DESC
`

type ListDeveloperMailboxesRow struct {
	ID        uuid.UUID
	Address   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) ListDeveloperMailboxes(ctx context.Context, createdBy uuid.NullUUID) ([]ListDeveloperMailboxesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeveloperMailboxes, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeveloperMailboxesRow
	for rows.Next() {
		var i ListDeveloperMailboxesRow
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMailbox = `-- name: UpsertMailbox :one

INSERT INTO mailboxes (
    id,
    address,
    expires_at,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (address)
DO UPDATE SET address = EXCLUDED.address
RETURNING id, address, created_at, expires_at, created_by
`

type UpsertMailboxParams struct {
	ID        uuid.UUID
	Address   string
	ExpiresAt time.Time
	CreatedBy uuid.NullUUID
}

func (q *Queries) UpsertMailbox(ctx context.Context, arg UpsertMailboxParams) (Mailbox, error) {
	row := q.db.QueryRowContext(ctx, upsertMailbox,
		arg.ID,
		arg.Address,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}
