// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getMessages = `-- name: GetMessages :many

SELECT
    id,
    sender,
    subject,
    created_at
FROM messages
WHERE address = $1
ORDER BY created_at DESC
LIMIT 50
`

type GetMessagesRow struct {
	ID        uuid.UUID
	Sender    string
	Subject   sql.NullString
	CreatedAt time.Time
}

func (q *Queries) GetMessages(ctx context.Context, address string) ([]GetMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Sender,
			&i.Subject,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawMessage = `-- name: GetRawMessage :one

SELECT
    id,
    sender,
    subject,
    created_at,
    raw
FROM messages
WHERE id = $1
  AND address = $2
`

type GetRawMessageParams struct {
	ID      uuid.UUID
	Address string
}

type GetRawMessageRow struct {
	ID        uuid.UUID
	Sender    string
	Subject   sql.NullString
	CreatedAt time.Time
	Raw       []byte
}

func (q *Queries) GetRawMessage(ctx context.Context, arg GetRawMessageParams) (GetRawMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getRawMessage, arg.ID, arg.Address)
	var i GetRawMessageRow
	err := row.Scan(
		&i.ID,
		&i.Sender,
		&i.Subject,
		&i.CreatedAt,
		&i.Raw,
	)
	return i, err
}
