// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Mailbox struct {
	ID        uuid.UUID
	Address   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Message struct {
	ID        uuid.UUID
	Sender    string
	Subject   sql.NullString
	MailboxID uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
	Raw       []byte
	Address   string
}
