// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks(id,developer_id,url,secret_encrypted,events) values ($1,$2,$3,$4,$5) RETURNING id,developer_id,url,is_active,events
`

type CreateWebhookParams struct {
	ID              uuid.UUID
	DeveloperID     uuid.UUID
	Url             string
	SecretEncrypted string
	Events          []string
}

type CreateWebhookRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Url         string
	IsActive    bool
	Events      []string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CreateWebhookRow, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ID,
		arg.DeveloperID,
		arg.Url,
		arg.SecretEncrypted,
		pq.Array(arg.Events),
	)
	var i CreateWebhookRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Url,
		&i.IsActive,
		pq.Array(&i.Events),
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :one
DELETE FROM webhooks
WHERE id = $1 AND developer_id = $2
RETURNING id
`

type DeleteWebhookParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteWebhook, arg.ID, arg.DeveloperID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, developer_id, url, secret_encrypted, is_active, events
FROM webhooks
WHERE id = $1 AND developer_id = $2
`

type GetWebhookParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

type GetWebhookRow struct {
	ID              uuid.UUID
	DeveloperID     uuid.UUID
	Url             string
	SecretEncrypted string
	IsActive        bool
	Events          []string
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (GetWebhookRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID, arg.DeveloperID)
	var i GetWebhookRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Url,
		&i.SecretEncrypted,
		&i.IsActive,
		pq.Array(&i.Events),
	)
	return i, err
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, developer_id, url, is_active, events
FROM webhooks
WHERE developer_id = $1
ORDER BY created_at DESC
`

type ListWebhooksRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Url         string
	IsActive    bool
	Events      []string
}

func (q *Queries) ListWebhooks(ctx context.Context, developerID uuid.UUID) ([]ListWebhooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhooksRow
	for rows.Next() {
		var i ListWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.DeveloperID,
			&i.Url,
			&i.IsActive,
			pq.Array(&i.Events),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
