// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package postgres

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks(id,developer_id,name,url,secret_encrypted,events) values ($1,$2,$3,$4,$5,$6) RETURNING id,developer_id,name,url,is_active,events
`

type CreateWebhookParams struct {
	ID              uuid.UUID
	DeveloperID     uuid.UUID
	Name            string
	Url             string
	SecretEncrypted string
	Events          []string
}

type CreateWebhookRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	Url         string
	IsActive    bool
	Events      []string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CreateWebhookRow, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ID,
		arg.DeveloperID,
		arg.Name,
		arg.Url,
		arg.SecretEncrypted,
		pq.Array(arg.Events),
	)
	var i CreateWebhookRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		pq.Array(&i.Events),
	)
	return i, err
}

const createWebhookDeadLetter = `-- name: CreateWebhookDeadLetter :exec
INSERT INTO webhook_dead_letters (
    id, developer_id, webhook_id, mailbox_id, message_id,
    event, url, reason, attempts
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWebhookDeadLetterParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	WebhookID   uuid.UUID
	MailboxID   uuid.NullUUID
	MessageID   uuid.NullUUID
	Event       string
	Url         string
	Reason      string
	Attempts    int32
}

func (q *Queries) CreateWebhookDeadLetter(ctx context.Context, arg CreateWebhookDeadLetterParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookDeadLetter,
		arg.ID,
		arg.DeveloperID,
		arg.WebhookID,
		arg.MailboxID,
		arg.MessageID,
		arg.Event,
		arg.Url,
		arg.Reason,
		arg.Attempts,
	)
	return err
}

const deleteEvents = `-- name: DeleteEvents :one
UPDATE webhooks w
SET events = ARRAY(
  SELECT unnest(events)
  EXCEPT
  SELECT unnest($3::text[])
)
WHERE w.id = $1
  AND w.developer_id = $2
RETURNING w.id, w.developer_id, w.name, w.url, w.is_active, w.events,
    COALESCE(
        ARRAY(SELECT wm.mailbox_id::uuid FROM webhook_mailboxes wm WHERE wm.webhook_id = w.id ORDER BY wm.mailbox_id::uuid),
        '{}'::uuid[]
    )::uuid[] AS mailbox_ids
`

type DeleteEventsParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Column3     []string
}

type DeleteEventsRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	Url         string
	IsActive    bool
	Events      []string
	MailboxIds  []uuid.UUID
}

func (q *Queries) DeleteEvents(ctx context.Context, arg DeleteEventsParams) (DeleteEventsRow, error) {
	row := q.db.QueryRowContext(ctx, deleteEvents, arg.ID, arg.DeveloperID, pq.Array(arg.Column3))
	var i DeleteEventsRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		pq.Array(&i.Events),
		pq.Array(&i.MailboxIds),
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :one
DELETE FROM webhooks
WHERE id = $1 AND developer_id = $2
RETURNING id
`

type DeleteWebhookParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteWebhook, arg.ID, arg.DeveloperID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT w.id, w.developer_id, w.name, w.url, w.secret_encrypted, w.is_active, w.events,
    COALESCE(
        ARRAY(SELECT wm.mailbox_id::uuid FROM webhook_mailboxes wm WHERE wm.webhook_id = w.id ORDER BY wm.mailbox_id::uuid),
        '{}'::uuid[]
    )::uuid[] AS mailbox_ids
FROM webhooks w
WHERE w.id = $1 AND w.developer_id = $2
`

type GetWebhookParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

type GetWebhookRow struct {
	ID              uuid.UUID
	DeveloperID     uuid.UUID
	Name            string
	Url             string
	SecretEncrypted string
	IsActive        bool
	Events          []string
	MailboxIds      []uuid.UUID
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (GetWebhookRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID, arg.DeveloperID)
	var i GetWebhookRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Url,
		&i.SecretEncrypted,
		&i.IsActive,
		pq.Array(&i.Events),
		pq.Array(&i.MailboxIds),
	)
	return i, err
}

const getWebhookMailbox = `-- name: GetWebhookMailbox :one
SELECT wm.webhook_id, wm.mailbox_id
FROM webhook_mailboxes wm
JOIN webhooks w ON w.id = wm.webhook_id AND w.developer_id = $3
WHERE wm.webhook_id = $1 AND wm.mailbox_id = $2
`

type GetWebhookMailboxParams struct {
	WebhookID   uuid.UUID
	MailboxID   uuid.UUID
	DeveloperID uuid.UUID
}

type GetWebhookMailboxRow struct {
	WebhookID uuid.UUID
	MailboxID uuid.UUID
}

func (q *Queries) GetWebhookMailbox(ctx context.Context, arg GetWebhookMailboxParams) (GetWebhookMailboxRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhookMailbox, arg.WebhookID, arg.MailboxID, arg.DeveloperID)
	var i GetWebhookMailboxRow
	err := row.Scan(&i.WebhookID, &i.MailboxID)
	return i, err
}

const getWebhooksByMailboxID = `-- name: GetWebhooksByMailboxID :many
SELECT w.id, w.developer_id, w.url, w.secret_encrypted, w.is_active, w.events
FROM webhooks w
JOIN webhook_mailboxes wm ON wm.webhook_id = w.id
WHERE wm.mailbox_id = $1
ORDER BY w.created_at DESC
`

type GetWebhooksByMailboxIDRow struct {
	ID              uuid.UUID
	DeveloperID     uuid.UUID
	Url             string
	SecretEncrypted string
	IsActive        bool
	Events          []string
}

func (q *Queries) GetWebhooksByMailboxID(ctx context.Context, mailboxID uuid.UUID) ([]GetWebhooksByMailboxIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getWebhooksByMailboxID, mailboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWebhooksByMailboxIDRow
	for rows.Next() {
		var i GetWebhooksByMailboxIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DeveloperID,
			&i.Url,
			&i.SecretEncrypted,
			&i.IsActive,
			pq.Array(&i.Events),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
UPDATE webhooks w
SET events = ARRAY(
    SELECT DISTINCT unnest(events || $3::text[])
)
WHERE w.id = $1
  AND w.developer_id = $2
RETURNING w.id, w.developer_id, w.name, w.url, w.is_active, w.events,
    COALESCE(
        ARRAY(SELECT wm.mailbox_id::uuid FROM webhook_mailboxes wm WHERE wm.webhook_id = w.id ORDER BY wm.mailbox_id::uuid),
        '{}'::uuid[]
    )::uuid[] AS mailbox_ids
`

type InsertEventParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Column3     []string
}

type InsertEventRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	Url         string
	IsActive    bool
	Events      []string
	MailboxIds  []uuid.UUID
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRowContext(ctx, insertEvent, arg.ID, arg.DeveloperID, pq.Array(arg.Column3))
	var i InsertEventRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		pq.Array(&i.Events),
		pq.Array(&i.MailboxIds),
	)
	return i, err
}

const linkWebhookMailbox = `-- name: LinkWebhookMailbox :one
INSERT INTO webhook_mailboxes(webhook_id, mailbox_id)
SELECT $1, m.id
FROM mailboxes m
JOIN webhooks w ON w.id = $1 AND w.developer_id = $3
WHERE m.id = $2 AND m.created_by = $3
ON CONFLICT (webhook_id, mailbox_id) DO NOTHING
RETURNING mailbox_id
`

type LinkWebhookMailboxParams struct {
	WebhookID   uuid.UUID
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

func (q *Queries) LinkWebhookMailbox(ctx context.Context, arg LinkWebhookMailboxParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, linkWebhookMailbox, arg.WebhookID, arg.ID, arg.DeveloperID)
	var mailbox_id uuid.UUID
	err := row.Scan(&mailbox_id)
	return mailbox_id, err
}

const listWebhookDeadLetters = `-- name: ListWebhookDeadLetters :many
SELECT d.id, d.webhook_id, d.mailbox_id, d.message_id, d.event, d.url, d.reason, d.attempts, d.created_at, d.seen,
    m.address AS mailbox_address,
    msg.sender AS message_sender,
    msg.subject AS message_subject
FROM webhook_dead_letters d
LEFT JOIN mailboxes m ON m.id = d.mailbox_id
LEFT JOIN messages msg ON msg.id = d.message_id
WHERE d.developer_id = $1
ORDER BY d.created_at DESC
LIMIT 100
`

type ListWebhookDeadLettersRow struct {
	ID             uuid.UUID
	WebhookID      uuid.UUID
	MailboxID      uuid.NullUUID
	MessageID      uuid.NullUUID
	Event          string
	Url            string
	Reason         string
	Attempts       int32
	CreatedAt      time.Time
	Seen           bool
	MailboxAddress sql.NullString
	MessageSender  sql.NullString
	MessageSubject sql.NullString
}

func (q *Queries) ListWebhookDeadLetters(ctx context.Context, developerID uuid.UUID) ([]ListWebhookDeadLettersRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookDeadLetters, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookDeadLettersRow
	for rows.Next() {
		var i ListWebhookDeadLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.MailboxID,
			&i.MessageID,
			&i.Event,
			&i.Url,
			&i.Reason,
			&i.Attempts,
			&i.CreatedAt,
			&i.Seen,
			&i.MailboxAddress,
			&i.MessageSender,
			&i.MessageSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT w.id, w.developer_id, w.name, w.url, w.is_active, w.events,
    COALESCE(
        ARRAY(SELECT wm.mailbox_id::uuid FROM webhook_mailboxes wm WHERE wm.webhook_id = w.id ORDER BY wm.mailbox_id::uuid),
        '{}'::uuid[]
    )::uuid[] AS mailbox_ids
FROM webhooks w
WHERE w.developer_id = $1
ORDER BY w.created_at DESC
`

type ListWebhooksRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	Url         string
	IsActive    bool
	Events      []string
	MailboxIds  []uuid.UUID
}

func (q *Queries) ListWebhooks(ctx context.Context, developerID uuid.UUID) ([]ListWebhooksRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks, developerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhooksRow
	for rows.Next() {
		var i ListWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.DeveloperID,
			&i.Name,
			&i.Url,
			&i.IsActive,
			pq.Array(&i.Events),
			pq.Array(&i.MailboxIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeadLetterSeen = `-- name: MarkWebhookDeadLetterSeen :one
UPDATE webhook_dead_letters
SET seen = TRUE
WHERE id = $1 AND developer_id = $2
RETURNING id
`

type MarkWebhookDeadLetterSeenParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
}

func (q *Queries) MarkWebhookDeadLetterSeen(ctx context.Context, arg MarkWebhookDeadLetterSeenParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, markWebhookDeadLetterSeen, arg.ID, arg.DeveloperID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const removeWebhookMailbox = `-- name: RemoveWebhookMailbox :one
DELETE FROM webhook_mailboxes wm
USING webhooks w
WHERE wm.webhook_id = w.id
  AND w.id = $1
  AND w.developer_id = $3
  AND wm.mailbox_id = $2
RETURNING wm.mailbox_id
`

type RemoveWebhookMailboxParams struct {
	ID          uuid.UUID
	MailboxID   uuid.UUID
	DeveloperID uuid.UUID
}

func (q *Queries) RemoveWebhookMailbox(ctx context.Context, arg RemoveWebhookMailboxParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, removeWebhookMailbox, arg.ID, arg.MailboxID, arg.DeveloperID)
	var mailbox_id uuid.UUID
	err := row.Scan(&mailbox_id)
	return mailbox_id, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks w
SET name = COALESCE(NULLIF($3::text, ''), name),
    is_active = $4::boolean,
    updated_at = CURRENT_TIMESTAMP
WHERE w.id = $1 AND w.developer_id = $2
RETURNING w.id, w.developer_id, w.name, w.url, w.is_active, w.events,
    COALESCE(
        ARRAY(SELECT wm.mailbox_id::uuid FROM webhook_mailboxes wm WHERE wm.webhook_id = w.id ORDER BY wm.mailbox_id::uuid),
        '{}'::uuid[]
    )::uuid[] AS mailbox_ids
`

type UpdateWebhookParams struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Column3     string
	Column4     bool
}

type UpdateWebhookRow struct {
	ID          uuid.UUID
	DeveloperID uuid.UUID
	Name        string
	Url         string
	IsActive    bool
	Events      []string
	MailboxIds  []uuid.UUID
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (UpdateWebhookRow, error) {
	row := q.db.QueryRowContext(ctx, updateWebhook,
		arg.ID,
		arg.DeveloperID,
		arg.Column3,
		arg.Column4,
	)
	var i UpdateWebhookRow
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		pq.Array(&i.Events),
		pq.Array(&i.MailboxIds),
	)
	return i, err
}
