import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/layout";
import { RootFooter } from "@/components/layout/RootFooter";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SwiftInBox",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > 
        <Header/>
    
          {children}
          <RootFooter />
          <Toaster
            position="bottom-right"
            duration={3000}
            closeButton
            expand={false}
            visibleToasts={Infinity}
            toastOptions={{
              classNames: {
                toast: "w-[min(calc(100vw-2rem),320px)] font-sans text-sm shadow-lg",
                title: "font-semibold tracking-normal",
                description: "text-xs leading-5",
                success: "border-zinc-200 bg-white text-zinc-900 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100",
                error: "border-red-200 bg-white text-red-600 dark:border-red-900 dark:bg-zinc-900 dark:text-red-400",
              },
            }}
            swipeDirections={["top", "left", "right"]}
          />
          </ThemeProvider></body>
    </html>
  );
}
